export const SMALL_VIEWPORT_WIDTH_BOUNDARY = 600;
export const SIZER_TOGGLE_WINDOW_WIDTH_TRIGGER_PX = SMALL_VIEWPORT_WIDTH_BOUNDARY;
export const DRAWER_TOGGLE_SMALL_SIZE_BOUNDARY = SMALL_VIEWPORT_WIDTH_BOUNDARY - 100;
