export enum ActionType {
  InitializeApp = '[APP_INITIALIZER] Initialize app',
  InitialPokeResourcesLoaded = '[EFFECT] Done initializing Pokes resources loaded',
  ReportAppInitialized = '[EFFECT] App initialization done',
  ReportAppRouteDataResolving = '[RESOLVER] App route data resolving',
  ReportAppRouteDataResolved = '[RESOLVER] App route data resolved',
  UpdateDisplayedPokes = '[EFFECT] Update displayed Pokes',
  UpdateDisplayedCaughtPokes = '[EFFECT] Update displayed caught Pokes',
  UpdateDisplayedWishlistedPokes = '[EFFECT] Update displayed wishlisted Pokes',
  ChangeDisplayedPokemons = '[COMPONENT] Change displayed Pokemons',
  ChangeDisplayedCaughtPokemons = '[COMPONENT] Change displayed caught Pokemons',
  ChangeDisplayedWishlistedPokemons = '[COMPONENT] Change displayed wishlisted Pokemons',
  CatchPokemon = '[COMPONENT] Catch a Pokemon',
  WishlistPokemon = '[COMPONENT] Wishlist a Pokemon',
  AddPokemonsToCaught = '[EFFECT] Add Pokemons to caught',
  AddPokemonsToWishlisted = '[EFFECT] Add Pokemons to wishlisted',
  ReleasePokemon = '[COMPONENT] Release a Pokemon',
  UnwishlistPokemon = '[COMPONENT] Unwishlist a Pokemon',
  RemovePokemonsFromCaught = '[EFFECT] Remove Pokemons from caught',
  RemovePokemonsFromWishlisted = '[EFFECT] Remove Pokemons from wishlist',
}
